services:
  pg-db:
    image: postgres:18-alpine3.22
    environment:
      POSTGRES_USER: prospera
      POSTGRES_PASSWORD: prospera
      POSTGRES_DB: prospera
    networks:
      - prospera-net
    ports:
      - "5432:5432" # Host 5432 → Container 5432
    volumes:
      - pg-prospera:/var/lib/postgresql/data

  rdb:
    image: redis:8.2-alpine
    env_file:
      - ./prod.env
    volumes:
      - redis-prospera:/data
    networks:
      - prospera-net
    ports:
      - 6379:6379

  backend:
    image: ghcr.io/radifan9/radif-prospera-wallet-backend:latest
    volumes:
      - ./prod.env:/app/.env
    networks:
      - prospera-net
    ports:
      - "8080:8080"
    depends_on:
      - pg-db
      - rdb


networks:
  prospera-net:

volumes:
  pg-prospera:
  redis-prospera: